#!/usr/bin/env python3
"""Render the name as a clean thin wordmark, on-theme, in an embedded font.

Not ascii-art: the name is set in a real typeface, subset to just its letters
and inlined as base64 woff2 so it renders identically on GitHub (which won't
fetch external fonts for an <img> SVG). Same grey ink, light/dark aware, with
the house left-to-right reveal and a cursor riding the edge.

Env: NAME_TEXT, NAME_FONT (ttf path), NAME_LS (letter-spacing), NAME_FS.
Output: name.svg (static; not regenerated by the daily Action).
"""
import base64
import io
import os

from fontTools import subset
from fontTools.ttLib import TTFont
from PIL import ImageFont

import generate_stats as g

TEXT = os.environ.get("NAME_TEXT", "Aswin Kumar")
OUT = os.environ.get("OUT_DIR", "..")
FONT = os.environ.get("NAME_FONT", r"C:\Windows\Fonts\corbel.ttf")
FS = float(os.environ.get("NAME_FS", "44"))
LS = float(os.environ.get("NAME_LS", "2"))
STROKE = float(os.environ.get("NAME_STROKE", "0.45"))  # a hair of faux-weight


def subset_face(path, text):
    font = TTFont(path)
    ss = subset.Subsetter()
    ss.populate(text=text + " ")
    ss.subset(font)
    font.flavor = "woff2"
    buf = io.BytesIO()
    font.save(buf)
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    return (f"@font-face{{font-family:NM;font-style:normal;font-weight:400;"
            f"font-display:block;src:url(data:font/woff2;base64,{b64}) "
            f"format('woff2')}}")


def build(text):
    face = subset_face(FONT, text)
    pil = ImageFont.truetype(FONT, int(FS))
    text_w = pil.getlength(text) + (len(text) - 1) * LS
    W = int(text_w + 8)
    H = int(FS * 1.30)
    baseline = int(FS * 0.95)

    # add a themed emph-stroke class (.es) so the faux-weight stroke matches the
    # ink in both light and dark
    style = g.style(font=face)
    style = style.replace("fill:#424a53}", "fill:#424a53}.es{stroke:#424a53}")
    style = style.replace("fill:#f0f6fc}", "fill:#f0f6fc}.es{stroke:#f0f6fc}")

    mono = "NM,ui-monospace,SFMono-Regular,Menlo,Consolas,monospace"
    p = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
         f'viewBox="0 0 {W} {H}" fill="none" font-family="{mono}">' + style]
    clip, cursor = g.wipe("nm", 0, 0, text_w + 4, H, 0.15, dur=1.05)
    p.append(clip)
    p.append('<g clip-path="url(#nm)">')
    cls = "e-f es" if STROKE else "e-f"
    sw = f' stroke-width="{STROKE}" paint-order="stroke"' if STROKE else ""
    p.append(f'<text x="0" y="{baseline}" class="{cls}"{sw} '
             f'font-size="{FS}" letter-spacing="{LS}" '
             f'xml:space="preserve">{text}</text>')
    p.append('</g>')
    p.append(cursor)
    p.append('</svg>')
    return "".join(p), W, H


def main():
    svg, W, H = build(TEXT)
    with open(os.path.join(OUT, "name.svg"), "w", encoding="utf-8") as f:
        f.write(svg)
    print(f"wrote name.svg  {W}x{H}  ({os.path.basename(FONT)})")


if __name__ == "__main__":
    main()
